local addon = TopDps

addon.CooldownRegistry:RegisterProfile({
    classToken = addon.Paladin.CLASS_TOKEN,
    talentTab = addon.Paladin.TALENT_TABS.HOLY,
    labelKey = "SPEC_PALADIN_HOLY",
})

addon.CooldownRegistry:RegisterProfile({
    classToken = addon.Paladin.CLASS_TOKEN,
    talentTab = addon.Paladin.TALENT_TABS.PROTECTION,
    labelKey = "SPEC_PALADIN_PROTECTION",
})

addon.CooldownRegistry:RegisterProfile({
    classToken = addon.Paladin.CLASS_TOKEN,
    talentTab = addon.Paladin.TALENT_TABS.RETRIBUTION,
    labelKey = "SPEC_PALADIN_RETRIBUTION",
})

addon.CooldownRegistry:Register({
    classToken = addon.Paladin.CLASS_TOKEN,
    entries = {
        {
            id = "avengingWrath",
            type = "spell",
            spellIds = { 31884 },
            group = addon.COOLDOWN_GROUP_OFFENSIVE,
            order = 10,
        },
        {
            id = "divineProtection",
            type = "spell",
            spellIds = { 498 },
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 10,
        },
        {
            id = "divineShield",
            type = "spell",
            spellIds = { 642 },
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 20,
        },
        {
            id = "handOfProtection",
            type = "spell",
            spellIds = { 1022, 5599, 10278 },
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 30,
        },
        {
            id = "handOfSacrifice",
            type = "spell",
            spellIds = { 6940 },
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 40,
        },
        {
            id = "layOnHands",
            type = "spell",
            spellIds = { 633, 2800, 10310, 27154, 48788 },
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 50,
        },
        {
            id = "handOfFreedom",
            type = "spell",
            spellIds = { 1044 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 10,
        },
        {
            id = "handOfSalvation",
            type = "spell",
            spellIds = { 1038 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 20,
        },
        {
            id = "handOfReckoning",
            type = "spell",
            spellIds = { 62124 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 30,
        },
        {
            id = "righteousDefense",
            type = "spell",
            spellIds = { 31789 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 40,
        },
        {
            id = "hammerOfJustice",
            type = "spell",
            spellIds = { 853, 5588, 5589, 10308 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 50,
        },
        {
            id = "divineIntervention",
            type = "spell",
            spellIds = { 19752 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 60,
        },
        {
            id = "divinePlea",
            type = "spell",
            spellIds = { 54428 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 70,
        },
        {
            id = "currentSeal",
            type = "aura",
            auraSpellIds = { 20154, 21084, 20164, 20165, 20166, 20375, 31801, 53736 },
            displaySpellId = 21084,
            name = addon.L.PALADIN_CURRENT_SEAL,
            inactiveText = "—",
            showDuration = false,
            group = addon.COOLDOWN_GROUP_STATES,
            order = 10,
        },
        {
            id = "sacredShield",
            type = "aura",
            auraSpellIds = { 53601 },
            displaySpellId = 53601,
            requiredSpellIds = { 53601 },
            auraUnit = "group",
            auraFilter = "HELPFUL",
            ownOnly = true,
            group = addon.COOLDOWN_GROUP_STATES,
            order = 20,
        },
    },
})

addon.CooldownRegistry:Register({
    classToken = addon.Paladin.CLASS_TOKEN,
    talentTab = addon.Paladin.TALENT_TABS.HOLY,
    entries = {
        {
            id = "holyShock",
            type = "spell",
            spellIds = { 20473, 20929, 20930, 27174, 33072, 48824, 48825 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 100,
        },
        {
            id = "divineFavor",
            type = "spell",
            spellIds = { 20216 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 110,
        },
        {
            id = "divineIllumination",
            type = "spell",
            spellIds = { 31842 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 120,
        },
        {
            id = "auraMastery",
            type = "spell",
            spellIds = { 31821 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 130,
        },
        {
            id = "beaconOfLight",
            type = "aura",
            auraSpellIds = { 53563 },
            displaySpellId = 53563,
            requiredSpellIds = { 53563 },
            auraUnit = "group",
            auraFilter = "HELPFUL",
            ownOnly = true,
            group = addon.COOLDOWN_GROUP_STATES,
            order = 30,
        },
        {
            id = "infusionOfLight",
            type = "aura",
            auraSpellIds = { 53672, 54149 },
            displaySpellId = 54149,
            group = addon.COOLDOWN_GROUP_PROCS,
            order = 10,
        },
        {
            id = "judgementsOfThePure",
            type = "aura",
            auraSpellIds = { 53655, 53656, 53657, 54152, 54153 },
            displaySpellId = 54153,
            group = addon.COOLDOWN_GROUP_PROCS,
            order = 20,
        },
        {
            id = "lightsGrace",
            type = "aura",
            auraSpellIds = { 31834 },
            displaySpellId = 31834,
            group = addon.COOLDOWN_GROUP_PROCS,
            order = 30,
        },
        {
            id = "sacredCleansing",
            type = "aura",
            auraSpellIds = { 53659 },
            displaySpellId = 53659,
            auraUnit = "group",
            auraFilter = "HELPFUL",
            ownOnly = true,
            group = addon.COOLDOWN_GROUP_PROCS,
            order = 40,
            defaultEnabled = false,
        },
    },
})

addon.CooldownRegistry:Register({
    classToken = addon.Paladin.CLASS_TOKEN,
    talentTab = addon.Paladin.TALENT_TABS.PROTECTION,
    entries = {
        {
            id = "avengersShield",
            type = "spell",
            spellIds = { 31935, 32699, 32700, 48826, 48827 },
            group = addon.COOLDOWN_GROUP_OFFENSIVE,
            order = 20,
        },
        {
            id = "divineSacrifice",
            type = "spell",
            spellIds = { 64205 },
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 60,
        },
        {
            id = "holyShield",
            type = "spell",
            spellIds = { 20925, 20927, 20928, 27179, 48951, 48952 },
            showStacks = true,
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 70,
        },
        {
            id = "ardentDefender",
            type = "aura",
            auraSpellIds = { 66233 },
            displaySpellId = 66233,
            auraUnit = "player",
            auraFilter = "HARMFUL",
            activeState = "COOLDOWN",
            inactiveState = "READY",
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 80,
        },
        {
            id = "divineGuardian",
            type = "aura",
            auraSpellIds = { 70940 },
            displaySpellId = 70940,
            auraUnit = "group",
            auraFilter = "HELPFUL",
            ownOnly = true,
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 90,
        },
        {
            id = "righteousFury",
            type = "aura",
            auraSpellIds = { 25780 },
            displaySpellId = 25780,
            inactiveText = "—",
            showDuration = false,
            group = addon.COOLDOWN_GROUP_STATES,
            order = 30,
        },
        {
            id = "redoubt",
            type = "aura",
            auraSpellIds = { 20132, 32776 },
            displaySpellId = 20132,
            showStacks = true,
            group = addon.COOLDOWN_GROUP_PROCS,
            order = 10,
        },
        {
            id = "reckoning",
            type = "aura",
            auraSpellIds = { 20178 },
            displaySpellId = 20178,
            showStacks = true,
            group = addon.COOLDOWN_GROUP_PROCS,
            order = 20,
        },
        {
            id = "sealStacks",
            type = "aura",
            auraSpellIds = { 31803, 53742 },
            displaySpellId = 31803,
            auraUnit = "target",
            auraFilter = "HARMFUL",
            ownOnly = true,
            showStacks = true,
            group = addon.COOLDOWN_GROUP_RESOURCES,
            order = 10,
        },
    },
})

addon.CooldownRegistry:Register({
    classToken = addon.Paladin.CLASS_TOKEN,
    talentTab = addon.Paladin.TALENT_TABS.RETRIBUTION,
    entries = {
        {
            id = "repentance",
            type = "spell",
            spellIds = { 20066 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 100,
        },
        {
            id = "artOfWar",
            type = "aura",
            auraSpellIds = { 59578, 53489 },
            displaySpellId = 59578,
            group = addon.COOLDOWN_GROUP_PROCS,
            order = 10,
        },
        {
            id = "vengeance",
            type = "aura",
            auraSpellIds = { 20050, 20052, 20053 },
            displaySpellId = 20053,
            showStacks = true,
            group = addon.COOLDOWN_GROUP_PROCS,
            order = 20,
        },
        {
            id = "sealStacks",
            type = "aura",
            auraSpellIds = { 31803, 53742 },
            displaySpellId = 31803,
            auraUnit = "target",
            auraFilter = "HARMFUL",
            ownOnly = true,
            showStacks = true,
            group = addon.COOLDOWN_GROUP_RESOURCES,
            order = 10,
        },
    },
})
