local addon = TopDps

addon.CooldownRegistry:Register({
    classToken = addon.Paladin.CLASS_TOKEN,
    entries = {
        {
            id = "avengingWrath",
            type = "spell",
            spellIds = { 31884 },
            group = addon.COOLDOWN_GROUP_OFFENSIVE,
            order = 10,
        },
        {
            id = "divineProtection",
            type = "spell",
            spellIds = { 498 },
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 10,
        },
        {
            id = "divineShield",
            type = "spell",
            spellIds = { 642 },
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 20,
        },
        {
            id = "handOfProtection",
            type = "spell",
            spellIds = { 1022, 5599, 10278 },
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 30,
        },
        {
            id = "handOfSacrifice",
            type = "spell",
            spellIds = { 6940 },
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 40,
        },
        {
            id = "divineSacrifice",
            type = "spell",
            spellIds = { 64205 },
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 50,
        },
        {
            id = "layOnHands",
            type = "spell",
            spellIds = { 633, 2800, 10310, 27154, 48788 },
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 60,
        },
        {
            id = "holyShield",
            type = "spell",
            spellIds = { 20925, 20927, 20928, 27179, 48951, 48952 },
            group = addon.COOLDOWN_GROUP_DEFENSIVE,
            order = 70,
        },
        {
            id = "handOfFreedom",
            type = "spell",
            spellIds = { 1044 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 10,
        },
        {
            id = "handOfSalvation",
            type = "spell",
            spellIds = { 1038 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 20,
        },
        {
            id = "handOfReckoning",
            type = "spell",
            spellIds = { 62124 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 30,
        },
        {
            id = "righteousDefense",
            type = "spell",
            spellIds = { 31789 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 40,
        },
        {
            id = "hammerOfJustice",
            type = "spell",
            spellIds = { 853, 5588, 5589, 10308 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 50,
        },
        {
            id = "repentance",
            type = "spell",
            spellIds = { 20066 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 60,
        },
        {
            id = "divineIntervention",
            type = "spell",
            spellIds = { 19752 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 70,
        },
        {
            id = "divineFavor",
            type = "spell",
            spellIds = { 20216 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 80,
        },
        {
            id = "divineIllumination",
            type = "spell",
            spellIds = { 31842 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 90,
        },
        {
            id = "auraMastery",
            type = "spell",
            spellIds = { 31821 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 100,
        },
        {
            id = "divinePlea",
            type = "spell",
            spellIds = { 54428 },
            group = addon.COOLDOWN_GROUP_UTILITY,
            order = 110,
        },
    },
})

addon.CooldownRegistry:Register({
    classToken = addon.Paladin.CLASS_TOKEN,
    specId = "PALADIN_RETRIBUTION",
    entries = {
        {
            id = "artOfWar",
            type = "aura",
            auraSpellIds = { 59578, 53489 },
            displaySpellId = 59578,
            group = addon.COOLDOWN_GROUP_PROCS,
            order = 10,
        },
    },
})
